name: Kymatio CI

on:
    - push
    - pull_request

jobs:
    build-pip-self-hosted:
        runs-on: self-hosted

        strategy:
            matrix:
                python-version: 3.8

        steps:
            - uses: actions/checkout@v1
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade pip
                  python3 -m pip install pytest pytest-cov

                  torch_version="1.7.1+cpu"
                  torchvision_version="0.8.2+cpu"

                  python3 -m pip install torch==${torch_version} torchvision==${torchvision_version} -f https://download.pytorch.org/whl/torch_stable.html

                  if [ "${{ matrix.python-version }}" != "3.9" ]; then
                      python3 -m pip install "tensorflow>=2.0.0a"
                  fi

                  python3 -m pip install scikit-learn

                  python3 -m pip install -r requirements.txt
                  python3 -m pip install -r requirements_optional.txt
            - name: Set up Kymatio
              run: python3 setup.py develop
            - name: Test
              run: pytest --cov=kymatio
